---
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: inno-hack-postgres
    restart: always
    ports:
      - '7071:5432'
    environment:
      PGUSER: user
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres

  backend:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=user

      - SERVER_PORT=7070
      - DEBUG=false

      - SECRET_KEY="!secret"
    build:
      dockerfile: backend/deploy/docker/api.Dockerfile
    container_name: inno-hack-api
    ports:
      - 7070:7070
    depends_on:
      - postgres
    
  frontend:
    container_name: inno-hack-react-app
    build:
      dockerfile: frontend/deploy/docker/front.Dockerfile
    ports:
      - 7072:7072
